account/urls.py
from django.urls import path

from account import views

app_name = "accounts"

urlpatterns = [
    path("",views.homepage,name="home"),
    path("login_form/",views.login_form,name="login_form"),
    path("login/",views.login_f,name="login"),
   path("logout/",views.logout_f,name="logout"),
path("changepassword/",views.changepassword,name="changepassowrd"),

    ]

quranproject/urls.py
from django.contrib import admin
from django.urls import path, include

import account

urlpatterns = [
    path("",include("account.urls")),
    path("manager/",include("manager.urls")),
path("teacher/",include("teacher.urls")),
path("student/",include("student.urls")),
    path('admin/', admin.site.urls),
    path('reset/', include('django.contrib.auth.urls')),
]

account/models.py
import os
import random

from django.contrib.auth.models import AbstractUser
from django.db import models
from datetime import datetime, timedelta
# Create your models here.
from account.barcodegenrator import MyBarcodeDrawing
gender_choices = (('Male',"Male"),
                ('Female',"Female"),)
day_choices=(
    ("السبت","السبت"),
    ("الأحد","الأحد"),
    ("الاثنين","الاثنين"),
    ("الثلاثاء","الثلاثاء"),
    ("الاربعاء","الاربعاء"),
    ("الخميس","الخميس"),
    ("الجمعة","الجمعة"),

)

absence_choices=(("parcode","parcode"),
                 ("teacher","teacher"),
)

homeworkdegreechoices=(("ممتاز","ممتاز"),
                       ("جيد جدا","جيد جدا"),
                       ("جيد","جيد"),
                       ("مقبول","مقبول"),
                       ("اعادة","اعادة"))


class user(AbstractUser):
    is_teacher = models.BooleanField(default=False)
    is_student = models.BooleanField(default=False)
    is_manager   = models.BooleanField(default=False)
    def save(self,*args,**kwargs):
        if "pbkdf2_sha256" != self.password.split("$")[0]:
            self.set_password(self.password)
        return super().save()


class surat(models.Model):
    name=models.CharField(max_length=255,null=False)
    numberinquran=models.PositiveIntegerField()
    numberofayat=models.PositiveIntegerField(null=True,blank=True)
    def __str__(self):
        return f"{self.name}"


class juz(models.Model):
    name=models.CharField(max_length=255,null=False)
    numberinquran = models.PositiveIntegerField()
    def __str__(self):
        return f"{self.name}"


class hizp(models.Model):
    name = models.CharField(max_length=255, null=False)
    numberinquran = models.PositiveIntegerField()
    def __str__(self):
        return f"{self.name}"


class ruba(models.Model):
    name = models.CharField(max_length=255, null=False)
    numberinquran = models.PositiveIntegerField()
    def __str__(self):
        return f"{self.name}"


class aya(models.Model):
    surat=models.ForeignKey(surat, on_delete=models.CASCADE, related_name='surat')
    juz=models.ForeignKey(juz, on_delete=models.CASCADE, related_name='juz',null=True)
    hizp=models.ForeignKey(hizp, on_delete=models.CASCADE, related_name='hizp',null=True)
    ruba=models.ForeignKey(ruba, on_delete=models.CASCADE, related_name='ruba',null=True)
    numberinsurat= models.PositiveIntegerField()
    numberinquran=models.PositiveIntegerField()
    def __str__(self):
        return f"{self.surat}:{self.numberinsurat}"


class Manager(models.Model):
    user = models.OneToOneField(user, on_delete=models.CASCADE, related_name='manager')

    def __str__(self):
        return f"{self.user.username}"


class Teacher(models.Model):
    user=models.OneToOneField(user, on_delete=models.CASCADE, related_name='teacher')
    manager=models.ForeignKey(Manager, on_delete=models.CASCADE, related_name='manager_teacher',null=True,blank=True)
    def __str__(self):
        return f"{self.user.username}"


class Lecture(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='lecture_teacher',null=True,blank=True)
    day=models.CharField(max_length=20,choices=day_choices)
    types = models.CharField(max_length=30,null=True,blank=True)
    hour=models.TimeField(null=True,blank=True)
    def __str__(self):
        return f"{self.teacher.user.username}-{self.day}-{self.hour}"

class Degree(models.Model):
    name=models.CharField(max_length=15,null=True,blank=True)
    def __str__(self):
        return f"{self.name}"

class Student(models.Model):
    user = models.OneToOneField(user, on_delete=models.CASCADE, related_name='student',null=True,blank=True)
    name=models.CharField(max_length=25, null=True,blank=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='student_teacher',null=True,blank=True)
    aya = models.ForeignKey(aya, on_delete=models.CASCADE, related_name='student_aya', null=True,blank=True)
    Achievements = models.CharField(max_length=2500, null=True,blank=True)
    barcode = models.CharField(max_length=2500, null=True,blank=True)
    degree=models.ForeignKey(Degree, on_delete=models.CASCADE, related_name='student_degree', null=True,blank=True)
    fathername = models.CharField(max_length=15, null=True, blank=True)
    fathernumber=models.CharField(max_length=20, null=True, blank=True)
    homework=models.CharField(max_length=2500, null=True,blank=True)
    gender=models.CharField(max_length=10,choices=gender_choices, null=True,blank=True)
    notpaid=models.BooleanField(null=True,blank=True)
    resoenofnotpaid=models.CharField(max_length=2500, null=True,blank=True)
    paid=models.BooleanField(null=True,blank=True)
    paymount=models.FloatField(null=True,blank=True)
    birthday=models.DateTimeField(null=True,blank=True)
    startlogin=models.DateTimeField(null=True,blank=True)
    finishlogin=models.DateTimeField(null=True,blank=True)

    def paidf(self):
        ds = datetime.now()
        df = ds + timedelta(30)
        self.startlogin = ds
        self.finishlogin = df
        self.paid=True
        self.save()
    def __str__(self):
        return f"{self.name}"
    def delete(self):
        os.remove(f"./static/barcodes/{self.user.username}.jpg")
        return super().delete()


class Student_Lecture(models.Model):
    lecture= models.ForeignKey(Lecture, on_delete=models.CASCADE, related_name='lecture_student')
    student=models.ForeignKey(Student, on_delete=models.CASCADE, related_name='student_lecture')


class Absence(models.Model):
    lecture = models.ForeignKey(Student_Lecture, on_delete=models.CASCADE, related_name='lecture_absence')
    day=models.DateTimeField(default=datetime.now())
    absence=models.BooleanField()
    homeworkdegree = models.CharField(max_length=20, choices=homeworkdegreechoices,null=True,blank=True)


class Settings(models.Model):
    manager=models.OneToOneField(Manager, on_delete=models.CASCADE, related_name='manager_settings',null=True,blank=True)
    absence=models.CharField(max_length=25,choices=absence_choices,default='parcode')

account/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from account.models import user


class UserSignUpForm(UserCreationForm):
    class Meta():
        model = user
        fields = ("username", "password1", "password2",)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "اسم المستخدم هذا الاسم يجب مختلفا عن باقي الاسماء يستخدمه في تسجيل الدخول "
        self.fields["password1"].label = "كلمة السر"
        self.fields["password2"].label = "تأكيد كلمة السر"

        for  field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = None

class UserUpdateForm(UserCreationForm):
    class Meta():
        model = user
        fields = ("username", "email", 'first_name', 'last_name',)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "اسم المستخدم"
        self.fields["email"].label = "البريد الالكترونى"
        self.fields["first_name"].label = "الاسم الاول "
        self.fields["last_name"].label = "الاسم الاخير"


        for  field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = None

class UserChangePasswordForm(UserCreationForm):
    class Meta():
        model = user
        fields = ( "password1", "password2",)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password1"].label = "كلمة السر"
        self.fields["password2"].label = "تأكيد كلمة السر"

        for  field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = None

account/views.py
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render

# Create your views here.
from django.urls import reverse

from account.forms import UserSignUpForm
from account.models import Teacher, surat, aya, user, Student
from quranproject.decrorator import stuff_required

listsurat= "البقرة-286,"
print(listsurat)

listsurat+="اّل عمران-200,\
النساء-176,\
المائدة-120,\
الانعام-165,\
الاعراف-206,\
الانفال-75,\
التوبة-129,\
يونس-109,\
هود-123,\
يوسف-111,\
الرعد-43,\
ابراهيم-52,\
الحجر-99,\
النحل-128,\
الاسراء-111,\
الكهف-110,\
مريم-98,\
طه-135,\
الانبياء-112,\
الحج-78,\
المؤمنون-118,\
النور-64,\
الفرقان-77,\
الشعراء-227,\
النمل-93,\
القصص-88,\
العنكبوت-69,\
الروم-60,\
لقمان-34,\
السجدة-30,\
الاحزاب-73,\
سبأ-54,\
فاطر-45,\
يس-83,\
الصافات-182,\
ص-88,\
الزمر-75,\
غافر-85,\
فصلت-54,\
الشوري-53,\
الزخرف-89,\
الدخان-59,\
الجاثية-37,\
الاحقاف-35,\
محمد-38,\
الفتح-29,\
الحجرات-18,\
ق-45,\
الذاريات-60,\
الطور-49,\
النجم-63,\
القمر-55,\
الرحمن-78,\
الواقعة-97,\
الحديد-29,\
المجادلة-22,\
الحشر-24,\
الممتحنة-13,\
الصف-14,\
الجمعة-11,\
المنافقون-11,\
التغابن-18,\
الطلاق-12,\
التحريم-12,\
الملك-30,\
القلم-52,\
الحاقة-52,\
المعارج-44,\
نوح-28,\
الجم-28,\
المزمل-20,\
المدثر-56,\
القيامة-40,\
الانسان-31,\
المرسلات-50,\
النبأ-40,\
النازعات-46,\
عبس-42,\
التكوير-29,\
الانفطار-19,\
المطففين-36,\
الانشقاق-25,\
البروج-22,\
الطارق-17,\
الاعلي-19,\
الغاشية-26,\
الفجر-30,\
البلد-20,\
الشمس-15,\
الليل-21,\
الضحي-11,\
الشرح-8,\
التين-8,\
العلق-19,\
القدر-5,\
البينة-8,\
الفيل-5,\
قريش-4,\
الماعون-7,\
الكوثر-3,\
الكافرون-6,\
النصر-3,\
المسد-5,\
الاخلاص-4,\
الفلق-5,\
الناس-6"



@login_required
def homepage(request):
    user=request.user
    print(type(user.password))
    if user.is_teacher:
        return render(request, "teacher_main_page.html", {})
    if user.is_student:
        return render(request, "student_main_page.html", {})
    if user.is_manager:
        return render(request, "manager_main_page.html", {})
    if user.is_superuser:
        return render(request, "base.html", {})


def login_form(request):
    print(request.GET)
    message=request.GET.get("err","")
    print(message)
    return render(request, "login.html", {
        'msg':message
    })


def login_f(request):

    username = request.POST.get('username')
    password = request.POST.get('password')
    print("name",username)
    print("pass",password)
    user = authenticate(username=username, password=password)
    if user is not None:
        print(user.is_superuser)
        if user.is_active:
            login(request, user)

            return HttpResponseRedirect(reverse('accounts:home'))
        else:
            return HttpResponseRedirect(reverse('accounts:login_form'))



    else:

            return HttpResponseRedirect(reverse('accounts:login_form')+"?err=اسم المستخدم او كلمة السر خطأ")

def logout_f(request):
    logout(request)
    return HttpResponseRedirect(reverse('accounts:home'))


@login_required
@stuff_required
def changepassword(request):
    password = request.POST.get("password", "0")
    print(password)
    code = request.POST.get("code", "0")
    student=Student.objects.filter(barcode=code).first()
    u=user.objects.filter(id=student.user.id).first()
    user.set_password(u,password)
    u.save()

    return HttpResponseRedirect(reverse('manager:changepassword'))

account/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V10</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="css/util.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
<!--===============================================================================================-->
</head>
<style>

/* BASIC */

html {
  background-color: #56baed;
}

body {
  font-family: "Poppins", sans-serif;
  height: 100vh;
}

a {
  color: #92badd;
  display:inline-block;
  text-decoration: none;
  font-weight: 400;
}

h2 {
  text-align: center;
  font-size: 16px;
  font-weight: 600;
  text-transform: uppercase;
  display:inline-block;
  margin: 40px 8px 10px 8px;
  color: #cccccc;
}



/* STRUCTURE */

.wrapper {
  display: flex;
  align-items: center;
  flex-direction: column;
  justify-content: center;
  width: 100%;
  min-height: 100%;
  padding: 20px;
}

#formContent {
  -webkit-border-radius: 10px 10px 10px 10px;
  border-radius: 10px 10px 10px 10px;
  background: #fff;
  padding: 30px;
  width: 90%;
  max-width: 450px;
  position: relative;
  padding: 0px;
  -webkit-box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
  box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
  text-align: center;
}

#formFooter {
  background-color: #f6f6f6;
  border-top: 1px solid #dce8f1;
  padding: 25px;
  text-align: center;
  -webkit-border-radius: 0 0 10px 10px;
  border-radius: 0 0 10px 10px;
}



/* TABS */

h2.inactive {
  color: #cccccc;
}

h2.active {
  color: #0d0d0d;
  border-bottom: 2px solid #5fbae9;
}



/* FORM TYPOGRAPHY*/

input[type=button], input[type=submit], input[type=reset]  {
  background-color: #56baed;
  border: none;
  color: white;
  padding: 15px 80px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  text-transform: uppercase;
  font-size: 13px;
  -webkit-box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
  box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
  margin: 5px 20px 40px 20px;
  -webkit-transition: all 0.3s ease-in-out;
  -moz-transition: all 0.3s ease-in-out;
  -ms-transition: all 0.3s ease-in-out;
  -o-transition: all 0.3s ease-in-out;
  transition: all 0.3s ease-in-out;
}

input[type=button]:hover, input[type=submit]:hover, input[type=reset]:hover  {
  background-color: #39ace7;
}

input[type=button]:active, input[type=submit]:active, input[type=reset]:active  {
  -moz-transform: scale(0.95);
  -webkit-transform: scale(0.95);
  -o-transform: scale(0.95);
  -ms-transform: scale(0.95);
  transform: scale(0.95);
}

.login {
  background-color: #f6f6f6;
  border: none;
  color: #0d0d0d;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 5px;
  width: 85%;
  border: 2px solid #f6f6f6;
  -webkit-transition: all 0.5s ease-in-out;
  -moz-transition: all 0.5s ease-in-out;
  -ms-transition: all 0.5s ease-in-out;
  -o-transition: all 0.5s ease-in-out;
  transition: all 0.5s ease-in-out;
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
}

.login:focus {
  background-color: #fff;
  border-bottom: 2px solid #5fbae9;
}

.login:placeholder {
  color: #cccccc;
}




/* ANIMATIONS */

/* Simple CSS3 Fade-in-down Animation */
.fadeInDown {
  -webkit-animation-name: fadeInDown;
  animation-name: fadeInDown;
  -webkit-animation-duration: 1s;
  animation-duration: 1s;
  -webkit-animation-fill-mode: both;
  animation-fill-mode: both;
}

@-webkit-keyframes fadeInDown {
  0% {
    opacity: 0;
    -webkit-transform: translate3d(0, -100%, 0);
    transform: translate3d(0, -100%, 0);
  }
  100% {
    opacity: 1;
    -webkit-transform: none;
    transform: none;
  }
}

@keyframes fadeInDown {
  0% {
    opacity: 0;
    -webkit-transform: translate3d(0, -100%, 0);
    transform: translate3d(0, -100%, 0);
  }
  100% {
    opacity: 1;
    -webkit-transform: none;
    transform: none;
  }
}

/* Simple CSS3 Fade-in Animation */
@-webkit-keyframes fadeIn { from { opacity:0; } to { opacity:1; } }
@-moz-keyframes fadeIn { from { opacity:0; } to { opacity:1; } }
@keyframes fadeIn { from { opacity:0; } to { opacity:1; } }

.fadeIn {
  opacity:0;
  -webkit-animation:fadeIn ease-in 1;
  -moz-animation:fadeIn ease-in 1;
  animation:fadeIn ease-in 1;

  -webkit-animation-fill-mode:forwards;
  -moz-animation-fill-mode:forwards;
  animation-fill-mode:forwards;

  -webkit-animation-duration:1s;
  -moz-animation-duration:1s;
  animation-duration:1s;
}

.fadeIn.first {
  -webkit-animation-delay: 0.4s;
  -moz-animation-delay: 0.4s;
  animation-delay: 0.4s;
}

.fadeIn.second {
  -webkit-animation-delay: 0.6s;
  -moz-animation-delay: 0.6s;
  animation-delay: 0.6s;
}

.fadeIn.third {
  -webkit-animation-delay: 0.8s;
  -moz-animation-delay: 0.8s;
  animation-delay: 0.8s;
}

.fadeIn.fourth {
  -webkit-animation-delay: 1s;
  -moz-animation-delay: 1s;
  animation-delay: 1s;
}

/* Simple CSS3 Fade-in Animation */
.underlineHover:after {
  display: block;
  left: 0;
  bottom: -10px;
  width: 0;
  height: 2px;
  background-color: #56baed;
  content: "";
  transition: width 0.2s;
}

.underlineHover:hover {
  color: #0d0d0d;
}

.underlineHover:hover:after{
  width: 100%;
}



/* OTHERS */

*:focus {
    outline: none;
}

#icon {
  width:60%;
}

</style>
<body>
	
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="wrapper fadeInDown">

   <p>{{msg}}</p>
  <div id="formContent">
    <!-- Tabs Titles -->

  <br>
      <br>
      <br>
    <form action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
      <input type="text" id="login" class="fadeIn second login" name="username" placeholder="username">
      <input type="password" id="password" class="fadeIn third login" name="password" placeholder="password">
      <input type="submit" class="fadeIn fourth" value="Log In">

    </form>

    <!-- Remind Passowrd -->

  </div>
</div>

</body>
</html>