account/urls.py
from django.urls import path

from account import views

app_name = "accounts"

urlpatterns = [
    path("",views.homepage,name="home"),
    path("login_form/",views.login_form,name="login_form"),
    path("login/",views.login_f,name="login"),
   path("logout/",views.logout_f,name="logout"),
path("changepassword/",views.changepassword,name="changepassowrd"),

    ]

quranproject/urls.py
from django.contrib import admin
from django.urls import path, include

import account

urlpatterns = [
    path("",include("account.urls")),
    path("manager/",include("manager.urls")),
path("teacher/",include("teacher.urls")),
path("student/",include("student.urls")),
    path('admin/', admin.site.urls),
    path('reset/', include('django.contrib.auth.urls')),
]

teacher/urls.py
from django.urls import path

from teacher import views

app_name = "teacher"

urlpatterns = [
    path("studentlist/",views.showStudent,name="studentlist"),
    path("updatestudentform/<int:id>",views.UpdateStudentForm,name="updatestudentform"),
    path("updatestudent/<int:id>",views.UpdateStudent,name="updatestudent"),
path("addstudentlectureform/<int:id>",views.addstudentlectureform,name="addstudentlectureform"),
path("addstudentlecture/<int:idstudent>/<int:idlecture>",views.addstudentlecture,name="addstudentlectureform"),


path("takeabsence/",views.takeabsence,name="takeabsence"),
path("absence/<int:id>/<str:abs>",views.absence,name="absence"),
path("checkabsence/<int:id>",views.checkabsence,name="checkabsence"),
    ]

teacher/models.py
from django.db import models

# Create your models here.

teacher/forms.py
from django import forms

from account.models import Teacher, Student

teacher/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render

# Create your views here.
from django.urls import reverse

from account.models import Student, aya, Lecture, Student_Lecture, Absence, surat, Degree
from manager.forms import HomeWorkDegree, StudentFormmanager, StudentFormSuperUser
from quranproject.decrorator import teacher_required, stuff_required, not_student_required

absdict={"true":True,
         "false":False}
dayoftheweek=["الاثنين","الثلاثاء","الأربعاء","الخميس","الجمعة","السبت","الأحد"]


@login_required
@teacher_required
def showStudent(request):
    num = request.GET.get("page", 1)
    objects =Student.objects.filter(teacher=request.user.teacher.id).all()
    # f = StudentgroupFilter(self.request.GET, queryset=objects)
    pages = Paginator(objects, 50)
    students = pages.page(num)
    context = {}
    '''context["name"] = self.request.GET.get("student__user__username", "")
    context["group"] = self.request.GET.get("group", "")
    context["filter"] = StudentgroupFilterForm(user1=self.request.user,
                                               initial={"student__user__username": context["name"],
                                                        "group": context["group"]})
    '''
    context['students'] = students
    context["pages"] = pages.page_range

    return render(request,"studentlist.html",context)

@login_required
@not_student_required
def UpdateStudentForm(request, id):
    user = request.user
    print(request.POST)
    student = Student.objects.filter(id=id).first()
    if user.is_manager:
        return render(request, "updatestudentm.html", {
            "student":student,
           "form_student":StudentFormmanager(user1=user,initial={
               "teacher":student.teacher,
               "name":student.name,
               "fathername":student.fathername,
               "fathernumber":student.fathernumber,
               "gender":student.gender,
               "notpaid":student.notpaid,
               "resoenofnotpaid":student.resoenofnotpaid,
               "paymount":student.paymount,
               "degree":student.degree,
           })
        })
    elif user.is_superuser:
        return render(request, "updatestudentm.html", {
            "student": student,
            "form_student": StudentFormmanager( initial={
                "teacher": student.teacher,
                "name": student.name,
                "fathername": student.fathername,
                "fathernumber": student.fathernumber,
                "gender": student.gender,
                "notpaid": student.notpaid,
                "resoenofnotpaid": student.resoenofnotpaid,
                "paymount": student.paymount,
                "degree": student.degree,
            })
        })

    homework=request.GET.get("homework","false")
    homework=absdict[homework]
    ida = int(request.GET.get("ida", 0))



    return render(request,"updatestudent.html",{
        "student":student,
        "homework":homework,
        "degree": HomeWorkDegree,
        "ida":ida
    })


@login_required
@stuff_required
def UpdateStudent(request,id):
    user=request.user
    print(request.POST)
    student = Student.objects.filter(id=id).first()
    newaya = request.POST.get("aya")
    degree=request.POST.get("degree")
    homework=request.POST.get("homework")
    homeworkdegree=request.POST.get("homeworkdegree",None)
    ida=int(request.POST.get("ida",0))
    degree=Degree.objects.filter(name=degree).first()
    if degree==None:
        degree=student.degree.id
    else:
        degree=degree.id
    if newaya == "":
        newaya=f'{student.aya.numberinsurat}:{student.aya.surat.numberinquran}'
    if homework == "":
        homework=f'{student.homework}'
    if len(newaya.split(":"))!= 2:
        return HttpResponseRedirect(reverse('manager:studentdetail', kwargs={'id': id})+f"?err=ادخل رقم اية في صورة صحيحة ")
    numberofnewaya=newaya.split(":")[0]
    numberofsuratofaya=newaya.split(":")[1]
    if not numberofsuratofaya.isnumeric():
        s=surat.objects.filter(name=numberofsuratofaya).first()
        if s==None:
            return HttpResponseRedirect(
                reverse('manager:studentdetail', kwargs={'id': id}) + f"?err=ادخل رقم اية في صورة صحيحة ")
        else:
            numberofsuratofaya=s.id
    a=aya.objects.filter(numberinsurat=int(numberofnewaya),surat__numberinquran=int(numberofsuratofaya)).first()
    if a== None:
        return HttpResponseRedirect(
            reverse('manager:studentdetail', kwargs={'id': id}) + f"?err=ادخل رقم اية في صورة صحيحة ")
    student.aya=a
    student.degree=degree
    student.homework=homework
    student.save()

    if homework:
        A = Absence.objects.filter(id=ida).first()
        A.homeworkdegree = homeworkdegree
        A.save()
        return HttpResponseRedirect(reverse('teacher:takeabsence')+f"hwseen={id}_{A.id}")
    return HttpResponseRedirect(reverse('manager:studentdetail',kwargs={'id': id}))

@login_required
@teacher_required
def addstudentlectureform(request,id):
    num = request.GET.get("page", 1)
    lecture=Lecture.objects.filter(id=id).first()
    objects = Student.objects.filter(teacher=lecture.teacher.id)\
        .exclude(student_lecture__in=Student_Lecture.objects.filter(lecture__id=id))\
        .all()
    print(objects)
    # f = StudentgroupFilter(self.request.GET, queryset=objects)
    pages = Paginator(objects, 50)
    students = pages.page(num)
    context = {}
    '''context["name"] = self.request.GET.get("student__user__username", "")
    context["group"] = self.request.GET.get("group", "")
    context["filter"] = StudentgroupFilterForm(user1=self.request.user,
                                               initial={"student__user__username": context["name"],
                                                        "group": context["group"]})
    '''
    context['students'] = students
    context["pages"] = pages.page_range
    context["lecture"]=lecture

    return render(request, "studentlecture.html", context)


@login_required
@teacher_required
def addstudentlecture(request,idstudent,idlecture):
    student=Student.objects.filter(id=idstudent).first()
    lecture = Lecture.objects.filter(id=idlecture).first()
    Student_Lecture(student=student,lecture=lecture).save()
    return JsonResponse({"id":idstudent})




@login_required
@teacher_required
def takeabsence(request):
    num = request.GET.get("page", 1)
    now1=datetime.datetime.now()
    H=now1.hour
    M=now1.minute
    now=datetime.time(H,M)
    weekday=dayoftheweek[datetime.datetime.today().weekday()]
    print(datetime.datetime.today())
    print(datetime.datetime.today().weekday())
    print(weekday)
    print("here error")
    lecture=Lecture.objects.filter(teacher=request.user.teacher.id,hour__lt=now,day=weekday)\
        .order_by("-hour")\
        .first()
    print(lecture)
    objects = Student_Lecture.objects.filter(lecture=lecture).all()
    # f = StudentgroupFilter(self.request.GET, queryset=objects)
    pages = Paginator(objects, 50)
    students = pages.page(num)
    context = {}

    '''context["name"] = self.request.GET.get("student__user__username", "")
    context["group"] = self.request.GET.get("group", "")
    context["filter"] = StudentgroupFilterForm(user1=self.request.user,
                                               initial={"student__user__username": context["name"],
                                                        "group": context["group"]})
    '''

    context['students'] = students
    context["pages"] = pages.page_range
    context["lecture"] = lecture


    return render(request, "takeabsence.html", context)
@login_required
@teacher_required
def absence(request,id,abs):
    student=Student_Lecture.objects.filter(id=int(id)).first()
    print(student)
    idstudent=student.student.id
    now=datetime.datetime.now()
    day=now.day
    month=now.month
    year=now.year
    today=datetime.datetime(year,month,day)
    A=Absence.objects.filter(lecture=student,day=today).first()
    if  A== None:
        A=Absence(lecture=student,day=today,absence=str(absdict[abs]))
        A.save()
    else:
        A.absence=absdict[abs]
        A.save()
    id=A.id
    return JsonResponse({"id":str(idstudent)+"_"+str(absdict[abs]),
                         "idc":str(idstudent)+"_"+ str(not absdict[abs]),
                         "ida":str(id)})
@login_required
@teacher_required
def checkabsence(request,id):
    num=request.GET.get("page", 1)
    lecture=Lecture.objects.filter(id=int(id)).first()
    now = datetime.datetime.now()
    day = now.day
    month = now.month
    year = now.year
    today = datetime.datetime(year, month, day)
    Abs=Absence.objects.filter(lecture__lecture=lecture,day=today).all()
    pages = Paginator(Abs, 50)
    Abs = pages.page(num)
    context=[]
    for i in Abs.object_list:
        ids=i.lecture.student.id
        statue=i.absence
        id = i.id
        context.append({
            "id": str(ids) + "_" + str(statue),
            "idc": str(ids) + "_" + str(not statue),
            "ida": str(id),
            "degree":i.homeworkdegree,
        })
    return JsonResponse({"res":context})

#

teacher/templates/studentlecture.html
{% extends 'base.html' %}
{% block style %}
<style>
    .notvalid
    {
    cursor: no-drop;
    }

</style>
       {% endblock style %}
{% block content %}
 <div class="col-md-12" >
     {{lecture}}
     <div class="content table-responsive table-full-width">

    <table id="studenttable" class="table table-hover table-striped" data-page-length='100' >
      <thead class="thead-light">
        <tr>
          <th>الرقم</th>
          <th>الاسم</th>
<th></th>

        </tr>
      </thead>
      <tbody>
      {% for student in students.object_list %}
      <tr>
       <td>{{forloop.counter}}</td>
          <td>{{student.user.username}}</td>
<td>
    <button  class='btn btn-primary'
       onclick="addstudent({{student.id}},{{lecture.id}})"
       id="{{student.id}}">اضافة</button></td>
     </tr>

      {% endfor %}
      </tbody>
    </table>
     </div>
 </div>
<div>
      <ul class="pagination" id="pagin">
          {% if students.has_previous %}
           <li class="page-item">
        <a class="page-link link-page" href="?page={{students.previous_page_number}}" style="display:inline-block" >prevpage</a>
    </li>
          {% else %}
           <li class="page-item">
        <a class="page-link link-page notvalid"  style="display:inline-block" disabled>prevpage</a>
    </li>
          {% endif %}
          {% for page in pages %}
    <li class="page-item">
        <a class="page-link link-page" href="?page={{page}}" style="display:none" >{{page}}</a>
    </li>
          {% endfor %}
         {% if students.has_next %}
           <li class="page-item">
        <a class="page-link link-page" href="?page={{students.next_page_number}}" style="display:inline-block" >nextpage</a>
    </li>
          {% else %}
           <li class="page-item">
        <a class="page-link link-page notvalid"  style="display:inline-block" disabled>next page</a>
    </li>
          {% endif %}
  </ul>
  </div>

{% endblock content %}

{% block script %}

<script>
console.log(window.location.href)
let url = new URL(window.location.href)
let params = new URLSearchParams(url.search);
let pages = params.get('page')
console.log(pages)

var eles=$(".link-page")
var l=eles.length

if(pages === null){
   console.log(pages)
   params.append("page", 1);
   pages=params.get('page')


}
if (pages < l ){
    console.log("first",eles[pages])
    eles[pages].style.display="inline-block";
if (pages != l-1){
console.log("sec",eles[Number(pages)+1])
    eles[Number(pages)+1].style.display="inline-block";
}
if (pages !=1){
console.log("th",eles[pages-1])
     eles[pages-1].style.display="inline-block"
}
}

function pageactive(ele){
    console.log("ele",ele)
}

function addstudent(idstudent,idlecture){
urllist=window.location.href.split("/");
console.log(urllist);
urllist.pop();
urllist.pop();
urllist.push("addstudentlecture");
urllist.push(idstudent);
urllist.push(idlecture);
url=urllist.join("/");
    fetch(url)
  .then(response => response.json())
  .then(data =>{

  ele=document.getElementById(`${data.id}`);
  ele.innerHTML="تمت الاضافة";
  ele.disabled=true;


  });

}
</script>

{% endblock script %}

teacher/templates/studentlist.html
{% extends 'base.html' %}
{% block style %}
<style>
    .notvalid
    {
    cursor: no-drop;
    }

</style>
       {% endblock style %}
{% block content %}
 <div class="col-md-12" >

     <div class="content table-responsive table-full-width">

    <table id="studenttable" class="table table-hover table-striped" data-page-length='100' >
      <thead class="thead-light">
        <tr>
          <th>الرقم</th>
          <th>الاسم</th>
<th></th>

        </tr>
      </thead>
      <tbody>
      {% for student in students.object_list %}
      <tr>
       <td>{{forloop.counter}}</td>
          <td>{{student.user.username}}</td>
<td>
   <a href="{% url 'teacher:updatestudentform' student.id %}"> <button class="btn btn-primary">تعديل بيانات الطالب</button> </a>
                      </td>
     </tr>

      {% endfor %}
      </tbody>
    </table>
     </div>
 </div>
<div>
      <ul class="pagination" id="pagin">
          {% if students.has_previous %}
           <li class="page-item">
        <a class="page-link link-page" href="?page={{students.previous_page_number}}" style="display:inline-block" >prevpage</a>
    </li>
          {% else %}
           <li class="page-item">
        <a class="page-link link-page notvalid"  style="display:inline-block" disabled>prevpage</a>
    </li>
          {% endif %}
          {% for page in pages %}
    <li class="page-item">
        <a class="page-link link-page" href="?page={{page}}" style="display:none" >{{page}}</a>
    </li>
          {% endfor %}
         {% if students.has_next %}
           <li class="page-item">
        <a class="page-link link-page" href="?page={{students.next_page_number}}" style="display:inline-block" >nextpage</a>
    </li>
          {% else %}
           <li class="page-item">
        <a class="page-link link-page notvalid"  style="display:inline-block" disabled>next page</a>
    </li>
          {% endif %}
  </ul>
  </div>

{% endblock content %}

{% block script %}

<script>

console.log(window.location.href)
let url = new URL(window.location.href)
let params = new URLSearchParams(url.search);
let pages = params.get('page')
console.log(pages)

var eles=$(".link-page")
var l=eles.length
if(pages === null){
   console.log(pages)
   params.append("page", 1);
   pages=params.get('page')


}
if (pages < l ){
    console.log("first",eles[pages])
    eles[pages].style.display="inline-block";
if (pages != l-1){
console.log("sec",eles[Number(pages)+1])
    eles[Number(pages)+1].style.display="inline-block";
}
if (pages !=1){
console.log("th",eles[pages-1])
     eles[pages-1].style.display="inline-block"
}
}

function pageactive(ele){
    console.log("ele",ele)
}

</script>

{% endblock script %}

teacher/templates/takeabsence.html
{% extends 'base.html' %}
{% block style %}
<style>
    .notvalid
    {
    cursor: no-drop;
    }

</style>
       {% endblock style %}
{% block content %}
 <div class="col-md-12" >
     {{lecture}}
     <div class="content table-responsive table-full-width">

    <table id="studenttable" class="table table-hover table-striped" data-page-length='100' >
      <thead class="thead-light">
        <tr>
          <th>الرقم</th>
          <th>الاسم</th>
<th></th>
<th></th>
            <th></th>
            <th></th>
        </tr>
      </thead>
      <tbody>
      {% for stu in students.object_list %}
      <tr>
       <td>{{forloop.counter}}</td>
          <td>{{stu.student.user.username}}</td>
<td>
    <button  class='btn btn-primary '
       onclick="takeabsence({{stu.id}},false)"
       id="{{stu.student.id}}_False"
             >حاضر</button></td>
          <td>
    <button  class='btn btn-primary '
       onclick="takeabsence({{stu.id}},true)"
       id="{{stu.student.id}}_True"
             >غائب</button></td>
           <td>
    <button id="{{stu.student.id}}" onclick="homework(event)" class='btn btn-primary' disabled>عرض الواجب </button></td>
     </tr>


      {% endfor %}
      </tbody>
    </table>
     </div>
 </div>
<div>
      <ul class="pagination" id="pagin">
          {% if students.has_previous %}
           <li class="page-item">
        <a class="page-link link-page" href="?page={{students.previous_page_number}}" style="display:inline-block" >prevpage</a>
    </li>
          {% else %}
           <li class="page-item">
        <a class="page-link link-page notvalid"  style="display:inline-block" disabled>prevpage</a>
    </li>
          {% endif %}
          {% for page in pages %}
    <li class="page-item">
        <a class="page-link link-page" href="?page={{page}}" style="display:none" >{{page}}</a>
    </li>
          {% endfor %}
         {% if students.has_next %}
           <li class="page-item">
        <a class="page-link link-page" href="?page={{students.next_page_number}}" style="display:inline-block" >nextpage</a>
    </li>
          {% else %}
           <li class="page-item">
        <a class="page-link link-page notvalid"  style="display:inline-block" disabled>next page</a>
    </li>
          {% endif %}
  </ul>
    <button  class='btn btn-primary '
       onclick="reload()"
             >اعادة تحميل</button>
  </div>

{% endblock content %}

{% block script %}

<script>
console.log(window.location.href)
let url = new URL(window.location.href)
let params = new URLSearchParams(url.search);
let pages = params.get('page')
console.log(pages)

var eles=$(".link-page")
var l=eles.length
if(pages === null){
   console.log(pages)
   params.append("page", 1);
   pages=params.get('page')


}
if (pages < l ){
    console.log("first",eles[pages])
    eles[pages].style.display="inline-block";
if (pages != l-1){
console.log("sec",eles[Number(pages)+1])
    eles[Number(pages)+1].style.display="inline-block";
}
if (pages !=1){
console.log("th",eles[pages-1])
     eles[pages-1].style.display="inline-block"
}
}

function pageactive(ele){
    console.log("ele",ele)
}

function reload(){
  location.reload()
}
function takeabsence(stuid,statue){
urllist=window.location.href.split("/");
console.log(urllist);
urllist.pop();
urllist.pop();
urllist.push("absence");
urllist.push(stuid);
urllist.push(statue);
url=urllist.join("/");
    fetch(url)
  .then(response => response.json())
  .then(data =>{

  ele1=document.getElementById(`${data.id}`);

  ele1.disabled=true;
  ele1.className+=`notvalid`

  ele2=document.getElementById(`${data.idc}`);
  ele2.disabled=false;
  ele2.className="btn btn-primary"

  statue=data.id.split("_")[1]
  id=data.id.split("_")[0]
  btn=document.getElementById(`${id}`);
   if(statue === "False"){
   btn.disabled=false;
   btn.className+=`btn btn-primary`
   btn.id=btn.id+"_"+data.ida
   }else{
   btn.disabled=true;
   btn.className+=`notvalid`
   }

  });
}



function homework(event){
urllist=window.location.href.split("/");
console.log(urllist);
urllist.pop();
urllist.pop();
urllist.push("updatestudentform");

console.log(event.target)
ids=event.target.id.split("_")[0]
ida=event.target.id.split("_")[1]
urllist.push(ids);

url=urllist.join("/");

window.location.href=url+"?homework=true&&ida="+ida



}

function check(id){
          urllist=window.location.href.split("/");
          console.log(urllist);
          urllist.pop();
          urllist.pop();
          urllist.push("checkabsence");
          urllist.push(id);
          url=urllist.join("/");
   fetch(url)
  .then(response => response.json())
  .then(data =>{
   console.log(data)
   datares=data.res
   for (const data of datares) {
         ele1=document.getElementById(`${data.id}`);

        ele1.disabled=true;
        ele1.className+=`notvalid`;

        ele2=document.getElementById(`${data.idc}`);
        ele2.disabled=false;
        ele2.className="btn btn-primary";

        statue=data.id.split("_")[1]
        id=data.id.split("_")[0]
        btn=document.getElementById(`${id}`);
        if(data.degree !== null){
            btn.innerHTML="تمت المشاهدة"
        }
        if(statue === "False"){
            btn.disabled=false;
            btn.className+=`btn btn-primary`
            btn.id=btn.id+"_"+data.ida
        }else{
             btn.disabled=true;
             btn.className+=`notvalid`
   }


}

  });
}
check({{lecture.id}})

/*if (performance.navigation.type == performance.navigation.TYPE_RELOAD) {
  check({{lecture.id}});
}*/


</script>

{% endblock script %}

teacher/templates/updatestudent.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<style>
/*body{
    margin-top:20px;
    color: #1a202c;
    text-align: left;
    background-color: #e2e8f0;
}
.main-body {
    padding: 15px;
}
.card {
    box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
}

.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid rgba(0,0,0,.125);
    border-radius: .25rem;
}

.card-body {
    flex: 1 1 auto;
    min-height: 1px;
    padding: 1rem;
}

.gutters-sm {
    margin-right: -8px;
    margin-left: -8px;
}

.gutters-sm>.col, .gutters-sm>[class*=col-] {
    padding-right: 8px;
    padding-left: 8px;
}
.mb-3, .my-3 {
    margin-bottom: 1rem!important;
}

.bg-gray-300 {
    background-color: #e2e8f0;
}
.h-100 {
    height: 100%!important;
}
.shadow-none {
    box-shadow: none!important;
}*/
</style>
       {% endblock style %}
{% block content %}
<div class="main-body">

          <!-- Breadcrumb -->

          <!-- /Breadcrumb -->

          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4>{{student.user.username}}</h4>

                     <a href="{% static 'barcodes' %}/{{student.user.username}}.jpg"> <button class="btn btn-primary">تحميل صورة الباركوود</button> </a>
                    </div>
                  </div>
                </div>
              </div>

            </div>

            <form method="post" action="{% url 'teacher:updatestudent' student.id %}" class="col-md-8" id="studentform">
              {% csrf_token %}

              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">الاسم</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{student.name}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">اسم الشيخ</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{student.teacher.user.username}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">مقدار الحفظ</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <input type="text" class="mb-0" placeholder="الحفظ" name="aya" style="display:block"><span>رقم السورة في القرءان : رقم الاية في السورة مثلا 2:1 الاية الثانية في سورة الفاتحة</span>
                    </div>
                  </div>
                  <hr>
                   {% if homework %}
                  <input type="hidden" value="{{ida}}" name="ida">
                    <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">المستوى</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{student.degree}}
                    </div>
                  </div>
                  <hr>
                      <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">الواجب السابق</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{student.homework}}
                    </div>
                  </div>
                  <hr>
                        <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">مستوى الواجب</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{degree}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">الواجب القادم</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <textarea form="studentform" class="mb-0" placeholder="الواجب" name="homework"
                                style="display:block"
                        rows="5" cols="30" maxlength="2500" ></textarea>

                    </div>
                  </div>
                  <hr>

                  {% else %}

                   <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">الواجب القادم</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{student.homework}}
                    </div>
                  </div>
                  <hr>

                    <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">المستوى</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">

                      <input type="text" class="mb-0" placeholder="المستوى" name="degree" style="display:block">
                    </div>
                  </div>
                  <hr>
                  {% endif %}


                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0"> المواظبة على الحضور</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                     المواظبة على الحضور
                    </div>
                  </div>
                </div>
              </div>


                  <input type="submit" value="تعديل بيانات الطلاب">
            </form>
          </div>
        </div>

{% endblock content %}

{% block script %}
<script>

</script>

       {% endblock script %}