account/urls.py
from django.urls import path

from account import views

app_name = "accounts"

urlpatterns = [
    path("",views.homepage,name="home"),
    path("login_form/",views.login_form,name="login_form"),
    path("login/",views.login_f,name="login"),
   path("logout/",views.logout_f,name="logout"),
path("changepassword/",views.changepassword,name="changepassowrd"),

    ]

manager/urls.py
from django.urls import path

from manager import views

app_name = "manager"

urlpatterns = [
    path("addteacherform/",views.addTeacherForm,name="addteacherform"),
path("addteacher/",views.addTeacher,name="addteacher"),
    path("teacherlist/",views.showTeacher,name="teacherlist"),
path("teacherdetail/<int:id>",views.teacherdetail,name="teacherdetail"),



 path("addstudentform/",views.addStudentForm,name="addstudentform"),
path("addstudent/",views.addStudent,name="addstudent"),
path("updatestudent/<int:pk>",views.StudentUpdateView.as_view(),name="updatestudent"),
    path("studentlist/",views.showStudent,name="studentlist"),
path("studentdetail/<int:id>",views.studentdetail,name="studentdetail"),
path("paidstudent/<int:id>",views.paidstudent,name="paid"),
path("studentlistteacher/<int:id>",views.showStudentTeacher,name="studentlistteacher"),


path("addlectureform/",views.addLecturetForm,name="addlectureform"),
path("addlecture/",views.addLecture,name="addlecture"),
    path("lecturelist/",views.showLecture,name="lecturelist"),
path("lecturedetail/<int:id>",views.lecturedetail,name="lecturedetail"),
path("studentlecturelist/<int:id>",views.showStudentLecture,name="studentlecturelist"),
path("lecturelisttecaher/<int:id>",views.showLectureTeacher,name="lecturelistteacher"),

path("abscentbyparcode/",views.absecntbarcode,name="absecntparcode"),
path("readparcode/",views.getstbarcode,name="readparcode"),

path("changepassword/",views.changepassword,name="changepassword"),

    ]

quranproject/urls.py
from django.contrib import admin
from django.urls import path, include

import account

urlpatterns = [
    path("",include("account.urls")),
    path("manager/",include("manager.urls")),
path("teacher/",include("teacher.urls")),
path("student/",include("student.urls")),
    path('admin/', admin.site.urls),
    path('reset/', include('django.contrib.auth.urls')),
]

student/urls.py
from django.urls import path

from student import views

app_name = "student"

urlpatterns = [
    path("studentabscent/",views.gettheabscent,name="studenabscent"),
    path("studentabscentdata/<int:id>",views.gettheabscentdata,name="studenabscentdata"),
    ]

teacher/urls.py
from django.urls import path

from teacher import views

app_name = "teacher"

urlpatterns = [
    path("studentlist/",views.showStudent,name="studentlist"),
    path("updatestudentform/<int:id>",views.UpdateStudentForm,name="updatestudentform"),
    path("updatestudent/<int:id>",views.UpdateStudent,name="updatestudent"),
path("addstudentlectureform/<int:id>",views.addstudentlectureform,name="addstudentlectureform"),
path("addstudentlecture/<int:idstudent>/<int:idlecture>",views.addstudentlecture,name="addstudentlectureform"),


path("takeabsence/",views.takeabsence,name="takeabsence"),
path("absence/<int:id>/<str:abs>",views.absence,name="absence"),
path("checkabsence/<int:id>",views.checkabsence,name="checkabsence"),
    ]

manager/models.py
from django.db import models

# Create your models here.

manager/forms.py
from django import forms

from account.models import Teacher, Student, Lecture, Absence


class StudentFormmanager(forms.ModelForm):

    degree=forms.CharField()
    class Meta():
        model = Student
        exclude = ("user","aya",
                   "barcode","startlogin","finishlogin",
                   "Achievements","homework",
                   "paid","degree","birthday")

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user1', None)
        super().__init__(*args, **kwargs)
        self.fields["teacher"].label="المدرس"
        self.fields["name"].label = "الاسم هذا الاسم الذي سيظهر للمدرس"
        self.fields["fathername"].label = "اسم ولي الامر"
        self.fields["fathernumber"].label = "رقم ولي الامر"
        self.fields["gender"].label = "الجنس"
        self.fields["notpaid"].label = "معفي من الدفع"
        self.fields["resoenofnotpaid"].label = "سبب الاعفاء"
        self.fields["paymount"].label = "قيمة الدفع اذا لم يكن معفيا"
        self.fields["degree"].label = "المستوى"
        self.fields["degree"].required = False
        if user != None:
            self.fields["teacher"].queryset=Teacher.objects.filter(manager=user.manager).all()
        for  field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = None



class StudentFormSuperUser(forms.ModelForm):
    degree = forms.CharField()
    class Meta():
        model = Student
        exclude = ("user", "aya",
                   "barcode", "startlogin", "finishlogin",
                   "Achievements", "homework",
                   "paid", "degree", "birthday")

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)
        self.fields["teacher"].label = "المدرس"
        self.fields["name"].label = "الاسم هذا الاسم الذي سيظهر للمدرس"
        self.fields["fathername"].label = "اسم ولي الامر"
        self.fields["fathernumber"].label = "رقم ولي الامر"
        self.fields["gender"].label = "الجنس"
        self.fields["notpaid"].label = "معفي من الدفع"
        self.fields["resoenofnotpaid"].label = "سبب الاعفاء"
        self.fields["paymount"].label = "قيمة الدفع اذا لم يكن معفيا"
        self.fields["degree"].label = "المستوى"
        self.fields["degree"].required = False
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = None


class LectureCreateForm(forms.ModelForm):

    class Meta():
        model = Lecture
        exclude=("hour","teacher",)
        fields='__all__'

class LectureCreateTeacherForm(forms.ModelForm):

    class Meta():
        model = Lecture
        fields=("teacher",)

    def __init__(self, *args, **kwargs):
        teachers = kwargs.pop('teachers')

        super().__init__(*args, **kwargs)
        self.fields['teacher'].queryset = teachers
        for  field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = None

class HomeWorkDegree(forms.ModelForm):

    class Meta():
        model = Absence
        fields=("homeworkdegree",)

manager/views.py
import datetime
import random

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import UpdateView

from account.barcodegenrator import MyBarcodeDrawing
from account.forms import UserSignUpForm
from account.models import Teacher, Student, aya, Lecture, Absence, Student_Lecture, Degree
from manager.filter import StudentFilterFormSuperUser, StudentFilterFormTeacher, \
    StudentFilterFormManager, StudentFilter
from manager.forms import LectureCreateForm, LectureCreateTeacherForm, HomeWorkDegree, StudentFormmanager
from quranproject.decrorator import manager_required, stuff_required
from teacher.views import dayoftheweek


@login_required
@manager_required
def addTeacherForm(request):
    err=request.GET.get("err","")
    return render(request,"addteacher.html",{
        'form':UserSignUpForm,
        "error":err
    })
@login_required
@manager_required
def addTeacher(request):
    user_form = UserSignUpForm(request.POST)

    if user_form.is_valid() :
        user = user_form.save(commit=False)
        user.set_password(user_form.cleaned_data['password2'])
        user.is_teacher=True
        user.save()
        print(request.user.is_manager)

        teacher=Teacher(user=user,manager=request.user.manager)
        teacher.save()
        return HttpResponseRedirect(reverse('manager:addteacherform')+"?statue=successed")

    else:
        return HttpResponseRedirect(reverse('manager:addteacherform')+f"?statue=falsed&&err={user_form.errors}")
@login_required
@manager_required
def showTeacher(request):
    context = {}
    num = request.GET.get("page", 1)
    objects = Teacher.objects.filter(manager=request.user.manager.id).all()
    # f = StudentgroupFilter(self.request.GET, queryset=objects)
    pages = Paginator(objects, 50)
    teachers = pages.page(num)

    '''context["name"] = request.GET.get("student__user__username", "")
    context["group"] = request.GET.get("group", "")
    context["filter_search"] = StudentgroupFilterFormManager(user1=request.user,
                                               initial={"student__user__username": context["name"],
                                                        "group": context["group"]})'''

    context['teachers'] = teachers
    context["pages"] = pages.page_range

    return render(request,"teacherlist.html",context)
@login_required
@manager_required
def teacherdetail(request,id):
    return render(request, "teacherdetail.html",{
        "teacher":Teacher.objects.filter(id=id).first()
    })



@login_required
@stuff_required
def addStudentForm(request):
    err=request.GET.get("err","")
    return render(request,"addstudent.html",{
        'form':UserSignUpForm,
        'form_student':StudentFormmanager(user1=request.user),
        "error":err
    })
@login_required
@stuff_required
def addStudent(request):
    user_form = UserSignUpForm(request.POST)
    student_form=StudentFormmanager(request.POST,user1=request.user)

    if user_form.is_valid() and student_form.save():

        while True:
            randomstring=''.join((random.choice("asdfergwqtyhujiklopnbvcxz12345678963258741") for i in range(15)))
            if (Student.objects.filter(barcode=randomstring).first() == None):
                break
        print(randomstring)
        user = user_form.save(commit=False)
        user.set_password(user_form.cleaned_data['password2'])
        user.is_student = True
        user.save()
        print(request.user.is_manager)

        student=student_form.save()
        student.user=user
        student.barcode=randomstring
        b = MyBarcodeDrawing(randomstring)
        b.save(formats=['jpg'], outDir='./static/barcodes/', fnRoot=f'{student.user.username}')
        student.save()

        return HttpResponseRedirect(reverse('manager:addstudentform')+"?statue=successed")
    else:
        return HttpResponseRedirect(reverse('manager:addstudentform')+f"?statue=falsed&&err={user_form.errors}")


@login_required
def showStudent(request):
    context = {}
    num = request.GET.get("page", 1)
    user=request.user
    name = request.GET.get("student__user__username", "")
    teacher = request.GET.get("teacher__id", "")
    degree = request.GET.get("degree__name", "")
    manager = request.GET.get("teacher__manager", "")
    if user.is_manager:
        objects = Student.objects.filter(teacher__manager=user.manager.id).all()
        context["filter"] = StudentFilterFormManager(user1=request.user,
                                                          initial={ "name": name,
                                                                    "teacher__id":teacher,
                                                                    "degree__name":degree,
                                                                    })
    elif user.is_teacher:
        objects = Student.objects.filter(teacher=user.teacher.id).all()
        context["filter"] = StudentFilterFormTeacher(user1=request.user,
                                                          initial={"name": name,
                                                                   "degree__name": degree,
                                                                   })

    else:
        objects = Student.objects.all()
        context["filter"] = StudentFilterFormSuperUser(user1=request.user,
                                                          initial={"name": name,
                                                                   "degree__name": degree,
                                                                   "teacher__manager":manager,
                                                                   "teacher__id":teacher
                                                                   })
    f = StudentFilter(request.GET, queryset=objects)
    pages = Paginator(f.qs,2)
    students = pages.page(num)

    context['students'] = students
    context["pages"] = pages.page_range

    return render(request,"studentlist.html",context)
@login_required
def studentdetail(request,id):

    total=Absence.objects.filter(lecture__student__id=id).all().count()
    print(total)
    notabsencetotel=Absence.objects.filter(lecture__student__id=id,absence=False).all().count()
    print(notabsencetotel)
    degree=(notabsencetotel/total)*100
    st=Student.objects.filter(id=id).first()
    if st.finishlogin != None:
        if st.finishlogin <= datetime.datetime.now():
            st.paid=False
            st.save()
    return render(request, "studentdetail.html",{
        "student":st,
        "absence":degree,

    })

@login_required
def paidstudent(request,id):
    st=Student.objects.filter(id=id).first()
    st.paidf()
    st.save()
    return JsonResponse({"id":1})



class StudentUpdateView(LoginRequiredMixin, UpdateView):
    model = Student
    form_class = StudentFormmanager

    def form_valid(self, *args, **kwargs):
        print("post", self.request.POST)
        name = self.request.POST.get("degree")
        degree = Degree.objects.filter(name=name).first()
        self.object.degree = degree if degree != None else self.object.degree
        self.object.save()
        return redirect('teacher:updatestudentform',  self.object.id)

''' def get_success_url(self):
        success_url = 
        return success_url'''





@login_required
@stuff_required
def addLecturetForm(request):
    err=request.GET.get("err","")
    if request.user.is_manager:
        teacher_form=LectureCreateTeacherForm(teachers=Teacher.objects.filter(manager__id=request.user.manager.id).all())
    else:
        teacher_form=None
    return render(request,"addlecture.html",{
        'form_lecture':LectureCreateForm(),
        "teacher_form":teacher_form,
        "error":err
    })
@login_required
@stuff_required
def addLecture(request):
    lecture_form = LectureCreateForm(request.POST)
    hour=request.POST.get("hour","0")
    print(hour)
    teacher_id=int(request.POST.get("teacher","0"))

    if request.user.is_manager:
        if teacher_id ==0:
            return HttpResponseRedirect(reverse('manager:addlectureform') + f"?statue=falsed&&err=please enter teacher")
        teacher=Teacher.objects.filter(id=teacher_id).first()
    else:
        teacher = Teacher.objects.filter(manager__id=request.user.teacher.id).first()
    if hour==0 :
        return HttpResponseRedirect(reverse('manager:addlectureform') + f"?statue=falsed&&err=please enter hour")

    if lecture_form.is_valid() :
        H=hour.split(":")[0]
        M=hour.split(":")[1]
        time=datetime.time(int(H),int(M))
        lecture=lecture_form.save()
        lecture.hour=time
        lecture.teacher=teacher
        lecture.save()
        return HttpResponseRedirect(reverse('manager:addlectureform')+"?statue=successed")

    else:
        return HttpResponseRedirect(reverse('manager:addlectureform')+f"?statue=falsed&&err={lecture_form.errors}")

@login_required
@stuff_required
def showLecture(request):
    num = request.GET.get("page", 1)
    if request.user.is_manager:
        objects = Lecture.objects.filter(teacher__manager=request.user.manager.id).all()
    else:
        objects = Lecture.objects.filter(teacher=request.user.teacher.id).all()
    # f = StudentgroupFilter(self.request.GET, queryset=objects)
    pages = Paginator(objects, 50)
    lectures = pages.page(num)
    context = {}
    '''context["name"] = self.request.GET.get("student__user__username", "")
    context["group"] = self.request.GET.get("group", "")
    context["filter"] = StudentgroupFilterForm(user1=self.request.user,
                                               initial={"student__user__username": context["name"],

manager/templates/abscentbarcode.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<style>
    .pointer {cursor: pointer;}
</style>
       {% endblock style %}
{% block content %}
 <h1>Pure JS Barcode Reader</h1>
<form action="{% url 'manager:readparcode' %}" method="post">
    {% csrf_token %}
  <input type="text" name="code" required>
  <button type="submit" id="go">Read Barcode</button>
    </form>
{% endblock content %}

{% block script %}

       {% endblock script %}

manager/templates/addlecture.html
{% extends 'base.html' %}
{% block style %}
<style>
    .pointer {cursor: pointer;}
</style>
       {% endblock style %}
{% block content %}
<form style="text-align:right" method="post" action="{% url 'manager:addlecture' %}" id="form">
    {% csrf_token %}
    {{form_lecture}}
    <label for="id_time">Types:</label>
    <input type="time" id="id_time" name="hour"
        required class="form-control">
    {{teacher_form}}
    <div style="text-align:center" >
    <input type="submit" value="اضافة درس" class="btn btn-success w-25 m-5 pointer"/>
    </div>
</form>

{% endblock content %}

{% block script %}
<script>
let url = new URL(window.location.href)
let params = new URLSearchParams(url.search);
let error = params.get('err')
let sucsses=params.get("statue")
var stringToHTML = function (str) {
	var parser = new DOMParser();
	var doc = parser.parseFromString(str, 'text/html');
	l=doc.body.childNodes
	console.log(doc.body)
	console.log(l)
	parent=document.getElementById("form")
	for (i of l[0].childNodes){
	    text=i.childNodes[0].textContent;
	    id="id_"+text;
	    console.log(id)
	    child=document.getElementById(id);
	    console.log(child)
	    parent.insertBefore(i.childNodes[1], child);
	}
};
stringToHTML(error)
let firstadd=true


if(sucsses === 'successed' && firstadd){
  alert("تمت اضافة الدرس")
  window.location.href=window.location.href.split("?")[0]
  firstadd=false
}
</script>

       {% endblock script %}

manager/templates/addstudent.html
{% extends 'base.html' %}
{% block style %}
<style>
    .pointer {cursor: pointer;}
</style>
       {% endblock style %}
{% block content %}
<form style="text-align:right" method="post" action="{% url 'manager:addstudent' %}" id="form">
    {% csrf_token %}
    {{form}}
    {{form_student}}
     <label for="birthday">يوم المولد</label>
  <input type="date" id="birthday" name="birthdaytime" class="form-control">
  <input type="submit">
    <div style="text-align:center" >
    <input type="submit" value="اضافة طالب" class="btn btn-success w-25 m-5 pointer"/>
    </div>
</form>

{% endblock content %}

{% block script %}
<script>
let url = new URL(window.location.href)
let params = new URLSearchParams(url.search);
let error = params.get('err')
let sucsses=params.get("statue")
var stringToHTML = function (str) {
	var parser = new DOMParser();
	var doc = parser.parseFromString(str, 'text/html');
	l=doc.body.childNodes
	console.log(doc.body)
	console.log(l)
	parent=document.getElementById("form")
	for (i of l[0].childNodes){
	    text=i.childNodes[0].textContent;
	    id="id_"+text;
	    console.log(id)
	    child=document.getElementById(id);
	    console.log(child)
	    parent.insertBefore(i.childNodes[1], child);
	}
};
stringToHTML(error)
let firstadd=true


if(sucsses === 'successed' && firstadd){
  alert("تمت اضافة الطالب بنجاح")
  window.location.href=window.location.href.split("?")[0]
  firstadd=false
}
</script>

       {% endblock script %}

manager/templates/changepassword.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<style>
    .pointer {cursor: pointer;}
</style>
       {% endblock style %}
{% block content %}
 <h1>Pure JS Barcode Reader</h1>
<form action="{% url 'accounts:changepassowrd' %}" method="post">
    {% csrf_token %}
    كلمة المرور:<input type="text" name="password" required> <br>
    <br>

    bar code:<input type="text" name="code" required>
    <br>

<button type="submit" id="go">تغيير كلمة المرور</button>

    </form>
{% endblock content %}

{% block script %}

       {% endblock script %}

manager/templates/lecturedetail.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<style>
/*body{
    margin-top:20px;
    color: #1a202c;
    text-align: left;
    background-color: #e2e8f0;
}
.main-body {
    padding: 15px;
}
.card {
    box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
}

.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid rgba(0,0,0,.125);
    border-radius: .25rem;
}

.card-body {
    flex: 1 1 auto;
    min-height: 1px;
    padding: 1rem;
}

.gutters-sm {
    margin-right: -8px;
    margin-left: -8px;
}

.gutters-sm>.col, .gutters-sm>[class*=col-] {
    padding-right: 8px;
    padding-left: 8px;
}
.mb-3, .my-3 {
    margin-bottom: 1rem!important;
}

.bg-gray-300 {
    background-color: #e2e8f0;
}
.h-100 {
    height: 100%!important;
}
.shadow-none {
    box-shadow: none!important;
}*/
</style>
       {% endblock style %}
{% block content %}
<div class="main-body">

          <!-- Breadcrumb -->

          <!-- /Breadcrumb -->

          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4>{{lecture.teacher.user.username}}</h4>
                      <a class="nav-link" href="{% url 'teacher:addstudentlectureform' lecture.id %}"> <button class="btn btn-primary">اضافة طلاب للمحاضرة</button> </a>
                      <a class="nav-link" href="{% url 'manager:studentlecturelist' lecture.id %}"> <button class="btn btn-primary">عرض طلاب للمحاضرة</button> </a>
                    </div>
                  </div>
                </div>
              </div>

            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">الاسم</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{lecture}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">اسم الشيخ</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{lecture.teacher.user.username}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">موعد الدرس</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                     {{lecture.day}} {{lecture.hour}}
                    </div>
                  </div>
                  <hr>



            </div>
          </div>
        </div>
{% endblock content %}

{% block script %}
<script>

</script>

       {% endblock script %}

manager/templates/studentdetail.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
{% if not student.paid %}
<script>

function paid(){
fetch("{% url 'manager:paid' student.id %}")
.then( res => res.json)
.then(data=>{
  document.getElementById(`paid`).style.display='none';
   document.getElementById(`statue`).innerHTML="دفع";



 })

}


</script>
{% endif %}
<style>
/*body{
    margin-top:20px;
    color: #1a202c;
    text-align: left;
    background-color: #e2e8f0;
}
.main-body {
    padding: 15px;
}
.card {
    box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
}

.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid rgba(0,0,0,.125);
    border-radius: .25rem;
}

.card-body {
    flex: 1 1 auto;
    min-height: 1px;
    padding: 1rem;
}

.gutters-sm {
    margin-right: -8px;
    margin-left: -8px;
}

.gutters-sm>.col, .gutters-sm>[class*=col-] {
    padding-right: 8px;
    padding-left: 8px;
}
.mb-3, .my-3 {
    margin-bottom: 1rem!important;
}

.bg-gray-300 {
    background-color: #e2e8f0;
}
.h-100 {
    height: 100%!important;
}
.shadow-none {
    box-shadow: none!important;
}*/
</style>
       {% endblock style %}
{% block content %}
<div class="main-body">

          <!-- Breadcrumb -->

          <!-- /Breadcrumb -->

          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4>{{student.name}}</h4>
                      {% if user.is_student %}
                      {% else %}
                      <a href="{% url 'teacher:updatestudentform' student.id %}"> <button class="btn btn-primary">تعديل بيانات الطالب</button> </a>
                      <hr>

                     <a href="{% static 'barcodes' %}/{{student.user.username}}.jpg"> <button class="btn btn-primary">تحميل صورة الباركوود</button> </a>
                   {% endif %}
                    </div>
                  </div>
                </div>
              </div>

            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">الاسم</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{student.name}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">اسم الشيخ</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{student.teacher.user.username}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">مقدار الحفظ</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{student.aya}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">المستوى</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{student.degree}}
                    </div>
                  </div>
                  <hr>
                   <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">الواجب</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{student.homework}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">

                    <div class="col-sm-3">
                      <h6 class="mb-0"> المواظبة على الحضور</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                    {{absence}}%   <a href="{% url 'student:studenabscentdata' student.id %}"
                                      class='btn btn-primary'>عرض سجل الغياب</a>
                    </div>
                  </div>
                    <hr>
                     <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0"> حالةالدفع</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                  {% if student.notpaid %}
                      معفي من الرسم بسبب {{student.resoenofnotpaid}}
                      {% elif student.paid %}
                         دفع
                      {% else %}
                        <span id="statue">لم يدفع</span>
                        <button onclick="paid()" id="paid" class='btn btn-primary'>
                            الدفع
                        </button>
                    {% endif %}
                    </div>
                  </div>
                </div>
              </div>

                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock content %}

{% block script %}


       {% endblock script %}

manager/templates/teacherdetail.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<style>

</style>
       {% endblock style %}
{% block content %}

 <div class="main-body">

          <!-- Breadcrumb -->

          <!-- /Breadcrumb -->


            <div class="col-md-12">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">الاسم</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{teacher.user.username}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">المحاضرات</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                    <a href="{% url 'manager:studentlistteacher' teacher.id %}"class='btn btn-primary'>المحاضرات</a>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">الطلاب</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                       <a href="{% url 'manager:lecturelistteacher' teacher.id %}"class='btn btn-primary'>الطلاب</a>
                    </div>
                  </div>

                </div>
              </div>

            </div>
          </div>
        </div>
{% endblock content %}

{% block script %}
<script>

</script>

       {% endblock script %}