account/urls.py
from django.urls import path

from account import views

app_name = "accounts"

urlpatterns = [
    path("",views.homepage,name="home"),
    path("login_form/",views.login_form,name="login_form"),
    path("login/",views.login_f,name="login"),
   path("logout/",views.logout_f,name="logout"),
path("changepassword/",views.changepassword,name="changepassowrd"),

    ]

manager/urls.py
from django.urls import path

from manager import views

app_name = "manager"

urlpatterns = [
    path("addteacherform/",views.addTeacherForm,name="addteacherform"),
path("addteacher/",views.addTeacher,name="addteacher"),
    path("teacherlist/",views.showTeacher,name="teacherlist"),
path("teacherdetail/<int:id>",views.teacherdetail,name="teacherdetail"),



 path("addstudentform/",views.addStudentForm,name="addstudentform"),
path("addstudent/",views.addStudent,name="addstudent"),
path("updatestudent/<int:pk>",views.StudentUpdateView.as_view(),name="updatestudent"),
    path("studentlist/",views.showStudent,name="studentlist"),
path("studentdetail/<int:id>",views.studentdetail,name="studentdetail"),
path("paidstudent/<int:id>",views.paidstudent,name="paid"),
path("studentlistteacher/<int:id>",views.showStudentTeacher,name="studentlistteacher"),


path("addlectureform/",views.addLecturetForm,name="addlectureform"),
path("addlecture/",views.addLecture,name="addlecture"),
    path("lecturelist/",views.showLecture,name="lecturelist"),
path("lecturedetail/<int:id>",views.lecturedetail,name="lecturedetail"),
path("studentlecturelist/<int:id>",views.showStudentLecture,name="studentlecturelist"),
path("lecturelisttecaher/<int:id>",views.showLectureTeacher,name="lecturelistteacher"),

path("abscentbyparcode/",views.absecntbarcode,name="absecntparcode"),
path("readparcode/",views.getstbarcode,name="readparcode"),

path("changepassword/",views.changepassword,name="changepassword"),

    ]

quranproject/urls.py
from django.contrib import admin
from django.urls import path, include

import account

urlpatterns = [
    path("",include("account.urls")),
    path("manager/",include("manager.urls")),
path("teacher/",include("teacher.urls")),
path("student/",include("student.urls")),
    path('admin/', admin.site.urls),
    path('reset/', include('django.contrib.auth.urls')),
]

student/urls.py
from django.urls import path

from student import views

app_name = "student"

urlpatterns = [
    path("studentabscent/",views.gettheabscent,name="studenabscent"),
    path("studentabscentdata/<int:id>",views.gettheabscentdata,name="studenabscentdata"),
    ]

teacher/urls.py
from django.urls import path

from teacher import views

app_name = "teacher"

urlpatterns = [
    path("studentlist/",views.showStudent,name="studentlist"),
    path("updatestudentform/<int:id>",views.UpdateStudentForm,name="updatestudentform"),
    path("updatestudent/<int:id>",views.UpdateStudent,name="updatestudent"),
path("addstudentlectureform/<int:id>",views.addstudentlectureform,name="addstudentlectureform"),
path("addstudentlecture/<int:idstudent>/<int:idlecture>",views.addstudentlecture,name="addstudentlectureform"),


path("takeabsence/",views.takeabsence,name="takeabsence"),
path("absence/<int:id>/<str:abs>",views.absence,name="absence"),
path("checkabsence/<int:id>",views.checkabsence,name="checkabsence"),
    ]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html dir="rtl" lang="ar">

<head>
    {% block title %}
       {% endblock title %}
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-iconpng' %}">
    <link rel="icon" type="image/png" href="{% static 'assets/img/faviconico' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Light Bootstrap Dashboard - Free Bootstrap 4 Admin Dashboard by Creative Tim</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <!-- CSS Files -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/light-bootstrap-dashboard.css' %}" rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="{% static 'assets/css/demo.css' %}" rel="stylesheet" />
    <style>
        .ml-auto {
    margin-left:0px;
}

.table>thead>tr>th{
text-align: right !important;
}

table {
    border-collapse:  separate;
}

    </style>
       {% block style %}
       {% endblock style %}
</head>

<body>
    <div class="wrapper">
        <div class="sidebar" data-image="{% static 'assets/img/sidebar-5.jpg' %}">
            <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

        Tip 2: you can also add an image using data-image tag
    -->    {% if user.is_teacher %}
          {% include 'sidebar_teacher.html' with user=user %}
            {% elif user.is_manager %}
               {% include 'sidebar_manager.html' with user=user %}
            {% elif user.is_superuser %}
                {% include 'sidebar_superuser.html' with user=user %}
            {% else %}
            {% include 'sidebar_student.html' with user=user %}
            {% endif %}
        </div>
        <div class="main-panel">
            <!-- Navbar -->
            {% include 'navbar_student.html' with user=user %}
            <!-- End Navbar -->
            <div class="content">
                <div class="container-fluid">
                    <div class="section">
                           {% block content %}
                           {% endblock content %}
                    </div>
                </div>
            </div>

            <footer class="footer">
                <div class="container-fluid">
                    <nav>

                        <p class="copyright text-center">
                            ©
                            <script>
                                document.write(new Date().getFullYear())
                            </script>
                            <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
                        </p>
                    </nav>
                </div>
            </footer>
        </div>
    </div>

</body>
<!--   Core JS Files   -->
<script src="{% static 'assets/js/core/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="{% static 'assets/js/plugins/bootstrap-switch.js' %}"></script>
<!--  Google Maps Plugin    -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!--  Chartist Plugin  -->
<script src="{% static 'assets/js/plugins/chartist.min.js' %}"></script>
<!--  Notifications Plugin    -->
<script src="{% static 'assets/js/plugins/bootstrap-notify.js' %}"></script>
<!-- Control Center for Light Bootstrap Dashboard: scripts for the example pages etc -->
<script src="{% static 'assets/js/light-bootstrap-dashboard.js' %}" type="text/javascript"></script>
<!-- Light Bootstrap Dashboard DEMO methods, don't include it in your project! -->
<script src="{% static 'assets/js/demo.js' %}"></script>
   {% block script %}
       {% endblock script %}
</html>

templates/manager_main_page.html
{% extends 'base.html' %}
{% load geturl %}
 {% block content %}
<p>لب مرحبا بك أيها المدير </p>

{% geturl request.GET.urlencode %}
{%endblock content %}

templates/navbar_student.html
  <nav class="navbar navbar-expand-lg " color-on-scroll="500">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#pablo">Template</a>
                    <button href="" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navigation">

                        <ul class="navbar-nav" style="text-align:left;">


                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:logout' %}">
                                    <span class="no-icon">Log out</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

templates/navbar_superuser.html
  <nav class="navbar navbar-expand-lg " color-on-scroll="500">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#pablo">Template</a>
                    <button href="" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navigation">

                        <ul class="navbar-nav" style="text-align:left;">


                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:logout' %}">
                                    <span class="no-icon">Log out</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

templates/sidebar_manager.html
   <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="javascript:;" class="simple-text">
                      Your Logo
                    </a>
                </div>
                <ul class="nav">
                     {% url 'manager:addteacherform' as addteacherform %}
                    <li class="nav-item {% if request.path == addteacherform %} active {% endif %} ">
                        <a class="nav-link" href="{% url 'manager:addteacherform' %}">
                            <i class="nc-icon nc-icon nc-paper-2"></i>
                            <p>اضافة مدرسين</p>
                        </a>
                    </li>
                    {% url 'manager:teacherlist' as teacherlist %}
                    <li class="nav-item {% if request.path == teacherlist %} active {% endif %}">

                        <a class="nav-link" href="{% url 'manager:teacherlist' %}">
                            <i class="nc-icon nc-icon nc-paper-2"></i>
                            <p>عرض مدرسين</p>
                        </a>
                    </li>
                      {% url 'manager:addstudentform' as addstudentform %}
                    <li class="nav-item {% if request.path == addstudentform %} active {% endif %}">
                        <a class="nav-link" href="{% url 'manager:addstudentform' %}">
                            <i class="nc-icon nc-icon nc-paper-2"></i>
                            <p>اضافة طلاب</p>
                        </a>
                    </li>
                     {% url 'manager:studentlist' as studentlist %}
                    <li class="nav-item {% if request.path == studentlist %} active {% endif %}">
                        <a class="nav-link" href="{% url 'manager:studentlist' %}">
                            <i class="nc-icon nc-icon nc-paper-2"></i>
                            <p>عرض الطلاب</p>
                        </a>
                    </li>
                      {% url 'manager:addlectureform' as addlectureform %}
                    <li class="nav-item {% if request.path == addlectureform %} active {% endif %}">
                        <a class="nav-link" href="{% url 'manager:addlectureform' %}">
                            <i class="nc-icon nc-bell-55"></i>
                            <p>اضافة مواعيد دروس</p>
                        </a>
                    </li>
                     {% url 'manager:lecturelist' as lecturelist %}
                    <li class="nav-item {% if request.path == lecturelist %} active {% endif %}">
                        <a class="nav-link" href="{% url 'manager:lecturelist' %}">
                            <i class="nc-icon nc-bell-55"></i>
                            <p>مواعيد الدروس</p>
                        </a>
                    </li>
                        {% url 'manager:absecntparcode' as absecntparcode %}
                    <li class="nav-item {% if request.path == absecntparcode %} active {% endif %}">
                        <a class="nav-link" href="{% url 'manager:absecntparcode' %}">
                            <i class="nc-icon nc-bell-55"></i>
                            <p>حضور وغياب</p>
                        </a>
                    </li>
                        {% url 'manager:changepassword' as changepassword %}
                    <li class="nav-item {% if request.path == changepassword %} active {% endif %}">
                        <a class="nav-link" href="{% url 'manager:changepassword' %}">
                            <i class="nc-icon nc-bell-55"></i>
                            <p>تغيير كلمة مرور الطالب</p>
                        </a>
                    </li>

                    <!--<li class="nav-item {% if request.path == addlectureform %} active {% endif %}">
                        <a class="nav-link active" href="javascript:;">
                            <i class="nc-icon nc-alien-33"></i>
                            <p>اعدادات</p>
                        </a>
                    </li>-->
                </ul>
            </div>

templates/sidebar_student.html
   <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="javascript:;" class="simple-text">
                      Your Logo
                    </a>
                </div>
                <ul class="nav">
                    {% url 'manager:studentdetail' as studentdetail %}
                    <li class="nav-item {% if request.path == studentdetail  %} active {% endif %}">
                        <a class="nav-link" href="{% url 'manager:studentdetail' user.student.id %}">
                            <i class="nc-icon nc-icon nc-paper-2"></i>
                            <p>بيانات الطالب</p>
                        </a>
                    </li>
                    <li>
                        {% url 'student:studenabscent' as studenabscent %}
                        <a class="nav-link {% if request.path == studenabscent  %} active {% endif %}"
                           href="{% url 'student:studenabscent' %}">
                            <i class="nc-icon nc-bell-55"></i>
                            <p>غياب الطالب</p>
                        </a>
                    </li>

                </ul>
            </div>

templates/sidebar_superuser.html
   <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="javascript:;" class="simple-text">
                      Your Logo
                    </a>
                </div>
                <ul class="nav">
                    {% url 'manager:studentlist' as studentlist %}
                    <li class="nav-item {% if request.path == studentlist %} active {% endif %}">
                        <a class="nav-link" href="{% url 'manager:studentlist' %}">
                            <i class="nc-icon nc-icon nc-paper-2"></i>
                            <p>عرض الطلاب</p>
                        </a>
                    </li>
                    <!--<li>
                        {% url 'student:studenabscent' as studenabscent %}
                        <a class="nav-link {% if request.path == studenabscent  %} active {% endif %}"
                           href="{% url 'student:studenabscent' %}">
                            <i class="nc-icon nc-bell-55"></i>
                            <p>غياب الطالب</p>
                        </a>
                    </li>-->

                </ul>
            </div>

templates/sidebar_teacher.html
   <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="javascript:;" class="simple-text">
                      Your Logo
                    </a>
                </div>

                <ul class="nav">
                   {% url 'manager:studentlist' as studentlist %}
                    <li class="nav-item {% if request.path == studentlist %} active {% endif %}">
                        <a class="nav-link" href="{% url 'manager:studentlist' %}">
                            <i class="nc-icon nc-icon nc-paper-2"></i>
                            <p>عرض الطلاب</p>
                        </a>
                    </li>
                    {% url 'manager:addlectureform' as addlectureform %}
                    <li>
                        <a class="nav-link {% if request.path ==  addlectureform  %} active {% endif %}"
                           href="{% url 'manager:addlectureform' %}">
                            <i class="nc-icon nc-bell-55"></i>
                            <p>اضافة مواعيد دروس</p>
                        </a>
                    </li>
                    {% url 'manager:lecturelist' as lecturelist %}
                    <li>
                        <a class="nav-link {% if request.path ==  lecturelist  %} active {% endif %}"
                           href="{% url 'manager:lecturelist' %}">
                            <i class="nc-icon nc-bell-55"></i>
                            <p>مواعيد الدروس</p>
                        </a>
                    </li>

                     {% url 'teacher:takeabsence' as takeabsence %}
                    <li>
                        <a class="nav-link {% if request.path == takeabsence  %} active {% endif %}"
                           href="{% url 'teacher:takeabsence' %}">
                            <i class="nc-icon nc-bell-55"></i>
                            <p>الغياب والحضور</p>
                        </a>
                    </li>

                </ul>
            </div>

templates/student_main_page.html
{% extends 'base.html' %}

 {% block content %}
<p> مرحبا بك أسها الطالب</p>
{%endblock content %}

templates/teacher_main_page.html
{% extends 'base.html' %}

 {% block content %}
<p> مرحبا بك أيها الشيخ</p>
{%endblock content %}